/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbhang;

import entity.SanPham;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.FieldPosition;
import java.text.NumberFormat;
import java.text.ParsePosition;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DBConnection;

/**
 *
 * @author Admin
 */
public class HóaĐơn extends javax.swing.JFrame {

    /**
     * Creates new form HóaĐơn
     */
    DBConnection db;

    public HóaĐơn() {
        this.db = new DBConnection();
        initComponents();
        initable("Select MaHoaDon,TenKhachHang,TenNhanVien,NgayLapHoaDon,HoanThanh from HoaDON hd JOIN KhachHang kh ON kh.MaKhachHang=hd.MaKhachHang JOIN NhanVien nv ON nv.MaNhanVien =hd.MaNhanVien");
        tablechiethoadon("Select MaHoaDon,TenSanPham,SoLuong,GiaBan ,ThanhTien from ChiTietHoaDon cthd JOIN SanPham sp ON cthd.MaSanPham=sp.MaSanPham");
        tablesanpham("select MaSanPham,TenSanPham,GiaBan from SanPham ");
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_hoadon = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtmahoadon1 = new javax.swing.JTextField();
        txttenkhachhang = new javax.swing.JTextField();
        txtngaylap = new javax.swing.JTextField();
        txtnhanvien = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Hoadondaxuly = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_chitiethoadon = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_sanpham = new javax.swing.JTable();
        txtTongtien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InHóaĐơn = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        txtmahhd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtmahoadon = new javax.swing.JTextField();
        txtmasanpham = new javax.swing.JTextField();
        txtgiaban = new javax.swing.JTextField();
        txtthanhtien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        ThêmChiTiết = new javax.swing.JButton();
        Suachitiet = new javax.swing.JButton();
        xoachitiet = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(204, 255, 204));
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(60, 60));

        jButton4.setBackground(new java.awt.Color(102, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/quanlysanpham-1.png"))); // NOI18N
        jButton4.setText("Sản Phẩm");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(90, 93));
        jButton4.setMinimumSize(new java.awt.Dimension(90, 93));
        jButton4.setPreferredSize(new java.awt.Dimension(90, 93));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton6.setBackground(new java.awt.Color(153, 255, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/Hoa_Don_1.png"))); // NOI18N
        jButton6.setText("Hóa Đơn");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setMaximumSize(new java.awt.Dimension(70, 93));
        jButton6.setMinimumSize(new java.awt.Dimension(70, 93));
        jButton6.setPreferredSize(new java.awt.Dimension(63, 93));
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/loai-san-pham_1.png"))); // NOI18N
        jButton1.setText("Loại Sản Phẩm");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(90, 93));
        jButton1.setMinimumSize(new java.awt.Dimension(90, 93));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 90));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton8.setBackground(new java.awt.Color(153, 255, 255));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/nhanvien.png"))); // NOI18N
        jButton8.setText("Nhân Viên");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton8);

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/thong_ke_1.png"))); // NOI18N
        jButton2.setText("Thống Kê");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/khachHang.png"))); // NOI18N
        jButton5.setText("Khách Hàng");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMaximumSize(new java.awt.Dimension(90, 90));
        jButton5.setMinimumSize(new java.awt.Dimension(90, 90));
        jButton5.setPreferredSize(new java.awt.Dimension(70, 91));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        jButton9.setBackground(new java.awt.Color(153, 255, 255));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/doitac_1.png"))); // NOI18N
        jButton9.setText("Đối Tác");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setMaximumSize(new java.awt.Dimension(90, 90));
        jButton9.setMinimumSize(new java.awt.Dimension(90, 90));
        jButton9.setOpaque(false);
        jButton9.setPreferredSize(new java.awt.Dimension(90, 90));
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton9);

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/tro_giup_1.png"))); // NOI18N
        jButton3.setText("Trợ Gíup");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(90, 90));
        jButton3.setMinimumSize(new java.awt.Dimension(90, 90));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jButton7.setBackground(new java.awt.Color(153, 255, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/iocn_thoat_1.png"))); // NOI18N
        jButton7.setText("Thoát");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMaximumSize(new java.awt.Dimension(63, 91));
        jButton7.setMinimumSize(new java.awt.Dimension(63, 91));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton7);

        jButton10.setBackground(new java.awt.Color(153, 255, 255));
        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/icon_logout_1.png"))); // NOI18N
        jButton10.setText("Đăng Xuất");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setMaximumSize(new java.awt.Dimension(90, 91));
        jButton10.setMinimumSize(new java.awt.Dimension(90, 90));
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton10);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Danh Sách Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        tbl_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_hoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hoadonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_hoadon);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Mã Hóa Đơn:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Khách Hàng:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Ngày Lập Hóa Đơn:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText(" Nhân Viên:");

        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 0, 0));
        jButton11.setText("Thêm Hóa Đơn");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 0, 0));
        jButton12.setText("Xóa Hóa Đơn");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        Hoadondaxuly.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Hoadondaxuly.setForeground(new java.awt.Color(255, 0, 0));
        Hoadondaxuly.setText("Hóa Đơn đã xử lý");
        Hoadondaxuly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoadondaxulyActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 0, 0));
        jButton13.setText("Hóa Đơn Chưa Xử Lý");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 0, 0));
        jButton15.setText("Hoàn Thành");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(txttenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txtmahoadon1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton13)
                    .addComponent(Hoadondaxuly, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton15)
                            .addComponent(txtnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngaylap, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton11)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtngaylap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtmahoadon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txttenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hoadondaxuly)
                            .addComponent(jButton11))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton13)
                            .addComponent(jButton12)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton15)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Chi Tiết Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 51, 51))); // NOI18N

        tbl_chitiethoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_chitiethoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_chitiethoadonMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_chitiethoadon);

        jScrollPane3.setViewportView(jScrollPane4);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Danh Sách Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        tbl_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tbl_sanpham);

        jScrollPane5.setViewportView(jScrollPane6);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtTongtien.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Mã Hóa Đơn:");

        InHóaĐơn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        InHóaĐơn.setForeground(new java.awt.Color(255, 0, 0));
        InHóaĐơn.setText("In Hóa Đơn");

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 51, 204));
        jButton17.setText("Tổng Hóa Đơn:");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Mã Hóa Đơn:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Tên Sản Phẩm:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Gía Bán:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Thành Tiền:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Số Lượng");

        ThêmChiTiết.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ThêmChiTiết.setForeground(new java.awt.Color(255, 0, 0));
        ThêmChiTiết.setText("Thêm Chi Tiết");
        ThêmChiTiết.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThêmChiTiếtActionPerformed(evt);
            }
        });

        Suachitiet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Suachitiet.setForeground(new java.awt.Color(255, 0, 0));
        Suachitiet.setText("Sửa Chi Tiết");

        xoachitiet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        xoachitiet.setForeground(new java.awt.Color(255, 0, 0));
        xoachitiet.setText("Xóa Chi Tiết");
        xoachitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoachitietActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 0, 0));
        reset.setText("Reset");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(547, 547, 547)
                        .addComponent(reset)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(txtmahhd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(InHóaĐơn)
                        .addGap(35, 35, 35)
                        .addComponent(jButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(ThêmChiTiết)
                                            .addGap(78, 78, 78)
                                            .addComponent(Suachitiet)
                                            .addGap(8, 8, 8))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5))
                                            .addGap(23, 23, 23)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtmasanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtmahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel6))
                                            .addGap(18, 18, 18)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtthanhtien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtgiaban, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(xoachitiet, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtmahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtmasanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ThêmChiTiết)
                                    .addComponent(Suachitiet)
                                    .addComponent(xoachitiet)
                                    .addComponent(reset)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtmahhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InHóaĐơn)
                            .addComponent(jButton17)
                            .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setBorder(null);
        jMenu1.setText("Trang Chủ");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu6.setBorder(null);
        jMenu6.setText("Hóa Đơn");
        jMenu6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu6);

        jMenu7.setBorder(null);
        jMenu7.setText("Doanh Thu");
        jMenu7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu7);

        jMenu8.setBorder(null);
        jMenu8.setText("Trợ Gíup");
        jMenu8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void initable(String sql) {
        Vector rowheader = new Vector();
        rowheader.add("Mã Hóa Đơn");
        rowheader.add("Khách Hàng");
        rowheader.add("Nhân Viên");
        rowheader.add("Ngày Lập");
        rowheader.add("Hoàn Thành");
        Vector tmp = new Vector();
        ResultSet rs = db.getData(sql);
        try {
            while (rs.next()) {
                Vector rowdata = new Vector();
                rowdata.add(rs.getInt(1));
                rowdata.add(rs.getString("TenKhachHang"));
                rowdata.add(rs.getString("TenNhanVien"));
                rowdata.add(rs.getDate("NgayLapHoaDon"));
                rowdata.add(rs.getInt("HoanThanh"));
                tmp.add(rowdata);

            }
        } catch (SQLException ex) {
            Logger.getLogger(HóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbl_hoadon.setModel(new DefaultTableModel(tmp, rowheader));

    }

    public void tablechiethoadon(String sql) {
        Vector rowheader = new Vector();
        rowheader.add("Mã Hóa Đơn");
        rowheader.add("Tên Sản Phẩm");
        rowheader.add("Số Lượng");
        rowheader.add("Gía Bán");
        rowheader.add("Thành Tien ");
        Vector tmp = new Vector();
        ResultSet rs = db.getData(sql);
        try {
            while (rs.next()) {
                Vector rowdata = new Vector();
                rowdata.add(rs.getInt("MaHoaDon"));
                rowdata.add(rs.getString("TenSanPham"));
                rowdata.add(rs.getInt("SoLuong"));
                NumberFormat fm = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
                rowdata.add(fm.format(rs.getInt("GiaBan")));
                rowdata.add(fm.format(rs.getInt("ThanhTien")));
                tmp.add(rowdata);

            }
        } catch (SQLException ex) {
            Logger.getLogger(HóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbl_chitiethoadon.setModel(new DefaultTableModel(tmp, rowheader));

    }

    public void tablesanpham(String sql) {
        Vector rowheader = new Vector();
        rowheader.add("Mã Sản Phẩm");
        rowheader.add("Tên Sản Phẩm");
        rowheader.add("Gía");
        Vector tmp = new Vector();
        ResultSet rs = db.getData(sql);
        try {
            while (rs.next()) {
                Vector rowdata = new Vector();
                rowdata.add(rs.getInt("MaSanPham"));
                rowdata.add(rs.getString("TenSanPham"));
                NumberFormat fm = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
                rowdata.add(fm.format(rs.getInt("GiaBan")));

                tmp.add(rowdata);

            }
        } catch (SQLException ex) {
            Logger.getLogger(HóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbl_sanpham.setModel(new DefaultTableModel(tmp, rowheader));

    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          close();
        HóaĐơn giaodien= new HóaĐơn();
        giaodien.setSize(1273,700);
        giaodien.setLocationRelativeTo(null);
        giaodien.setVisible(true);
                
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        close();
        ThêmHóaĐơn themhoadon = new ThêmHóaĐơn();
        themhoadon.setLocationRelativeTo(null);
        themhoadon.setVisible(true);

    }//GEN-LAST:event_jButton11ActionPerformed

    private void tbl_hoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hoadonMouseClicked
        // TODO add your handling code here:
        int index = tbl_hoadon.getSelectedRow();
        int mahdd = Integer.parseInt(tbl_hoadon.getValueAt(index, 0).toString());
        txtmahoadon1.setText(String.valueOf(mahdd));
        txttenkhachhang.setText(tbl_hoadon.getValueAt(index, 1).toString());
        txtnhanvien.setText(tbl_hoadon.getValueAt(index, 2).toString());
        txtngaylap.setText(tbl_hoadon.getValueAt(index, 3).toString());
        txtmahhd.setText(String.valueOf(mahdd));
        txtmahoadon.setText(String.valueOf(mahdd));
        tablechiethoadon("Select MaHoaDon,TenSanPham,SoLuong,GiaBan ,ThanhTien from ChiTietHoaDon cthd JOIN SanPham sp ON cthd.MaSanPham=sp.MaSanPham where cthd.MaHoaDon='" + mahdd + "'");

    }//GEN-LAST:event_tbl_hoadonMouseClicked
    int click = 0;
    private void tbl_chitiethoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_chitiethoadonMouseClicked
        // TODO add your handling code here:
        int index = tbl_chitiethoadon.getSelectedRow();
        click++;
        if (index != -1) {
            int mahdd = Integer.parseInt(tbl_chitiethoadon.getValueAt(index, 0).toString());
            txtmahoadon.setText(String.valueOf(mahdd));
            txtmasanpham.setText(tbl_chitiethoadon.getValueAt(index, 1).toString());
            txtsoluong.setText(tbl_chitiethoadon.getValueAt(index, 2).toString());
            txtgiaban.setText(tbl_chitiethoadon.getValueAt(index, 3).toString());
            txtthanhtien.setText(tbl_chitiethoadon.getValueAt(index, 3).toString());
            txtmahhd.setText(String.valueOf(mahdd));

        }
    }//GEN-LAST:event_tbl_chitiethoadonMouseClicked

    private void HoadondaxulyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoadondaxulyActionPerformed
        // TODO add your handling code here:
        initable("Select MaHoaDon,TenKhachHang,TenNhanVien,NgayLapHoaDon,HoanThanh from HoaDON hd JOIN KhachHang kh ON kh.MaKhachHang=hd.MaKhachHang JOIN NhanVien nv ON nv.MaNhanVien =hd.MaNhanVien where HoanThanh=1 ");
    }//GEN-LAST:event_HoadondaxulyActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        initable("Select MaHoaDon,TenKhachHang,TenNhanVien,NgayLapHoaDon,HoanThanh from HoaDON hd JOIN KhachHang kh ON kh.MaKhachHang=hd.MaKhachHang JOIN NhanVien nv ON nv.MaNhanVien =hd.MaNhanVien where HoanThanh=0");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        int mahdd = Integer.parseInt(txtmahoadon.getText().toString());
        String sql = "Select SUM(ThanhTien)as TongTien from ChiTietHoaDon where MaHoaDon='" + mahdd + "'";

        ResultSet rs = db.getData(sql);
        try {
            while (rs.next()) {
                int tien = rs.getInt("TongTien");
                NumberFormat fm = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
                String tien1 = fm.format(tien);
                txtTongtien.setText(tien1);

            }
        } catch (SQLException ex) {
            Logger.getLogger(HóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        int mahd = Integer.parseInt(txtmahoadon1.getText().trim());
        String sql = "Select HoanThanh from HoaDon where MaHoaDon='" + mahd + "'";
        int HoanThanh = 0;
        ResultSet rs = db.getData(sql);
        try {
            while (rs.next()) {
                HoanThanh = rs.getInt("HoanThanh");

            }
        } catch (SQLException ex) {
            Logger.getLogger(HóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (HoanThanh == 1) {
            JOptionPane.showMessageDialog(this, "Hóa Đơn đã xử lý.Bạn không được phép sử lý");
        } else if (HoanThanh == 0) {
            String sql1 = "Update HoaDon set HoanThanh=1 where MaHoaDon='" + mahd + "'";
            db.ExcuteQueryUpdateDB(sql1);
            JOptionPane.showMessageDialog(this, "Thành Công");
            HóaĐơn giaodien = new HóaĐơn();
            giaodien.setSize(1273, 700);
            giaodien.setLocationRelativeTo(null);
            giaodien.setVisible(true);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int mahd = Integer.parseInt(txtmahoadon1.getText());
        String sql = "Select HoanThanh from HoaDon where MaHoaDon='" + mahd + "'";
        int HoanThanh = 0;
        ResultSet rs = db.getData(sql);
        try {
            while (rs.next()) {
                HoanThanh = rs.getInt("HoanThanh");

            }
        } catch (SQLException ex) {
            Logger.getLogger(HóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (HoanThanh == 0) {
//            int sophieu=0;
//            String sq="Select count(MaHoaDon) as sophieu from ChiTietHoaDon cthd JOIN HoaDon hd ON hd.MaHoaDon=cthd.MaHoaDon and MaHoaDon='"+mahd+"'";
//            ResultSet rs2= db.getData(sq);
//            try {
//                while(rs.next()){
//                    sophieu=rs.getInt("sophieu");
//                }
//            } catch (SQLException ex) {
//                Logger.getLogger(HóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            if(sophieu<0){
            String sql1 = "Delete HoaDon where MaHoaDon='" + mahd + "'";
            db.ExcuteQueryUpdateDB(sql1);
            JOptionPane.showMessageDialog(this, "Xóa Thành Công");
            HóaĐơn giaodien = new HóaĐơn();
            giaodien.setSize(1273, 700);
            giaodien.setLocationRelativeTo(null);
            giaodien.setVisible(true);
//            }
//            else{
//                JOptionPane.showMessageDialog(this, "Bạn Phải Xóa Chi Tiết Hóa Đơn trước!!!");
//            }
        }
        if (HoanThanh == 1) {
            JOptionPane.showMessageDialog(this, "Không được xóa");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void xoachitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoachitietActionPerformed
        // TODO add your handling code here:
        int mahd = Integer.parseInt(txtmahoadon1.getText().trim());
        String sql = "Select HoanThanh from HoaDon where MaHoaDon='" + mahd + "'";
        int HoanThanh = 0;
        ResultSet rs = db.getData(sql);
        try {
            while (rs.next()) {
                HoanThanh = rs.getInt("HoanThanh");

            }
        } catch (SQLException ex) {
            Logger.getLogger(HóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
        }
        String tensp = txtmasanpham.getText();

        if (HoanThanh == 0) {
            int masp = 0;
            String sql2 = "Select MaSanPham from SanPham where TenSanPham='" + tensp + "'";
            ResultSet rs1 = db.getData(sql2);

            try {
                while (rs1.next()) {
                    masp = rs1.getInt("MaSanPham");
                }
            } catch (SQLException ex) {
                Logger.getLogger(HóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
            }
            String sql1 = "Delete ChiTietHoaDon where MaSanPham='" + masp + "'";
            db.ExcuteQueryUpdateDB(sql1);
            JOptionPane.showMessageDialog(this, "Xóa Thành Công");
            HóaĐơn giaodien = new HóaĐơn();
            giaodien.setSize(1273, 700);
            giaodien.setLocationRelativeTo(null);
            giaodien.setVisible(true);
        }
        if (HoanThanh == 1) {
            JOptionPane.showMessageDialog(this, "Không được xóa");
        }
    }//GEN-LAST:event_xoachitietActionPerformed

    private void ThêmChiTiếtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThêmChiTiếtActionPerformed
        // TODO add your handling code here:
//        int mahd = Integer.parseInt(txtmahoadon.getText().trim());
//        String sql = "Select HoanThanh from HoaDon where MaHoaDon='" + mahd + "'";
//        int HoanThanh = 0;
//        ResultSet rs = db.getData(sql);
//        try {
//            while (rs.next()) {
//                HoanThanh = rs.getInt("HoanThanh");
//
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(HóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        String tensp = txtmasanpham.getText();
//        int masp = 0;
//        String sql2 = "Select MaSanPham from SanPham where TenSanPham='" + tensp + "'";
//        ResultSet rs1 = db.getData(sql2);
//
//        try {
//            while (rs1.next()) {
//                masp = rs1.getInt("MaSanPham");
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(HóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        if (HoanThanh == 0) {
//
//            String sql3 = "Select GiaBan from SanPham where MaSanPham='" + masp + "'";
//            int gia = 0;
//            ResultSet rs3 = db.getData(sql3);
//            try {
//                while (rs3.next()) {
//                    gia = rs.getInt("GiaBan");
//                }
//            } catch (SQLException ex) {
//                Logger.getLogger(HóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//            int soluong = Integer.parseInt(txtsoluong.getText());
//            int thanhtien = gia * soluong;
//            //  NumberFormat fm=NumberFormat.getCurrencyInstance(new Locale("vi","VN"));
//            txtgiaban.setText(String.valueOf(gia));
//            txtthanhtien.setText(String.valueOf(thanhtien));
//
//        }
//        String mahd1 = txtmahoadon.getText();
//        int soluong=Integer.parseInt(txtsoluong.getText());
//        String giaban=txtgiaban.getText();
//        String thanhtien=txtthanhtien.getText();
//        String sql4="Insert into ChiTietHoaDon (MaHoaDon,MaSanPham,gia,ThanhTien) values('"+mahd1+"','"+masp+"','"+giaban+"','"+thanhtien+"')";
//        db.ExcuteQueryUpdateDB(sql4);
        

    }//GEN-LAST:event_ThêmChiTiếtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          close();

                SảnPhẩm giaodien = new SảnPhẩm();
                giaodien.setSize(1273, 700);
                giaodien.setLocationRelativeTo(null);
                giaodien.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HóaĐơn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HóaĐơn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HóaĐơn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HóaĐơn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HóaĐơn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hoadondaxuly;
    private javax.swing.JButton InHóaĐơn;
    private javax.swing.JButton Suachitiet;
    private javax.swing.JButton ThêmChiTiết;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton reset;
    private javax.swing.JTable tbl_chitiethoadon;
    private javax.swing.JTable tbl_hoadon;
    private javax.swing.JTable tbl_sanpham;
    private javax.swing.JTextField txtTongtien;
    private javax.swing.JTextField txtgiaban;
    private javax.swing.JTextField txtmahhd;
    private javax.swing.JTextField txtmahoadon;
    private javax.swing.JTextField txtmahoadon1;
    private javax.swing.JTextField txtmasanpham;
    private javax.swing.JTextField txtngaylap;
    private javax.swing.JTextField txtnhanvien;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttenkhachhang;
    private javax.swing.JTextField txtthanhtien;
    private javax.swing.JButton xoachitiet;
    // End of variables declaration//GEN-END:variables

}
