/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbhang;

import entity.SanPham;
import javax.swing.JFrame;
import model.DBConnection;
import entity.SanPham;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import entity.ChiTietHoaDon;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;

/**
 *
 * @author Admin
 */
public class ThêmHóaĐơn extends javax.swing.JDialog {

    /**
     * Creates new form ThêmHóaĐơn
     */
    DBConnection db;
    SảnPhẩm aThis;
    SanPham sp;
    private PreparedStatement pre;

    ArrayList<ChiTietHoaDon> list = new ArrayList<>();

    Connection con;

    ThêmHóaĐơn() {
        this.db = new DBConnection();
        con = db.getConnection();
        initComponents();
        loadmahdd();
        getcbb("select MaKhachHang from KhachHang", "MaKhachHang", cbbmakhachang);
        getcbb("select MaNhanVien from NhanVien", "MaNhanVien", cbbmanhanvien);

    }

    ThêmHóaĐơn(SảnPhẩm aThis, boolean b, SanPham sp) {
        this.aThis = aThis;
        this.db = new DBConnection();
        this.sp = sp;
        initComponents();
        intt();
        loadmahdd();
        getcbb("select MaKhachHang from KhachHang", "MaKhachHang", cbbmakhachang);
        getcbb("select MaNhanVien from NhanVien", "MaNhanVien", cbbmanhanvien);
    }

    public void intt() {

        txtmasanpham.setText(String.valueOf(sp.getMaSanPham()));
        txttensanpham.setText(sp.getTenSanPham());
        txtloaisanpham.setText(sp.getTenLoaiSanPham());
        //txtloaisanpham.setText(getTenLoaiSanPham(sp.getMaLoaiSanPham()));
        txtgiaban.setText(String.valueOf(sp.getGiaBan()));

    }

    public DefaultComboBoxModel getcbb(String sql, String colum1, JComboBox cbb) {

        DefaultComboBoxModel cbbmodel = new DefaultComboBoxModel();
        ResultSet rs = db.getData(sql);
        try {
            while (rs.next()) {
                int ma = rs.getInt(colum1);
                cbbmodel.addElement(ma);
                cbb.setModel(cbbmodel);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThêmHóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
        }
        return cbbmodel;

    }

    public void loadmahdd() {
        String sql = "select count(*) from HoaDON";
        ResultSet rs = db.getData(sql);
        int counthd = 0;
        try {
            while (rs.next()) {
                counthd = rs.getInt(1);
                txtmahoadon.setText(String.valueOf(counthd + 1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThêmHóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtmahoadon = new javax.swing.JTextField();
        cbbmakhachang = new javax.swing.JComboBox<>();
        txttenkhachhang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbbmanhanvien = new javax.swing.JComboBox<>();
        txttennahnvien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_hoadon = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtloaisanpham = new javax.swing.JTextField();
        txtmasanpham = new javax.swing.JTextField();
        txttensanpham = new javax.swing.JTextField();
        txtsoluong = new javax.swing.JTextField();
        btThemChiTiet = new javax.swing.JButton();
        btThem = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtgiaban = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TXTNGAY = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setIconImages(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Thêm Hóa Đơn");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Mã Hóa Đơn:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Mã Khách Hàng:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Tên Khách Hàng:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Tên Nhân Viên:");

        cbbmakhachang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbmakhachang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbmakhachangActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Mã Nhân Viên:");

        cbbmanhanvien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbmanhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbmanhanvienActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Hoàn Thành:");

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setText("Yes");

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton2.setText("No");

        tbl_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_hoadon);

        jScrollPane1.setViewportView(jScrollPane2);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Chọn Sản Phẩm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtloaisanpham.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtloaisanpham.setForeground(new java.awt.Color(255, 51, 51));
        txtloaisanpham.setToolTipText("Loại Sản Phẩm");

        txtmasanpham.setToolTipText("Mã Sản Phẩm");

        txttensanpham.setToolTipText("Tên Sản Phẩm");

        txtsoluong.setToolTipText("Số lượng");

        btThemChiTiet.setBackground(new java.awt.Color(51, 255, 255));
        btThemChiTiet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btThemChiTiet.setForeground(new java.awt.Color(255, 0, 0));
        btThemChiTiet.setText("Thêm Chi Tiết ");
        btThemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemChiTietActionPerformed(evt);
            }
        });

        btThem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btThem.setForeground(new java.awt.Color(255, 0, 0));
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/thêm.jpg"))); // NOI18N
        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        jButton3.setText("Thoát");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Ngày Lập:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmahoadon, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(cbbmanhanvien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbmakhachang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TXTNGAY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(61, 61, 61)
                                .addComponent(jRadioButton2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txttenkhachhang)
                                .addComponent(txttennahnvien, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 590, Short.MAX_VALUE)
                .addComponent(btThem)
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addGap(186, 186, 186))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jButton1)
                .addGap(43, 43, 43)
                .addComponent(txtloaisanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(txtmasanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txttensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btThemChiTiet)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtmahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel2)
                            .addGap(58, 58, 58))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txttenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(39, 39, 39)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbbmakhachang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txttennahnvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TXTNGAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtloaisanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmasanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThemChiTiet))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(jButton3))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SảnPhẩm sp = new SảnPhẩm();
        sp.setSize(1273, 700);
        sp.setVisible(true);
        sp.setLocationRelativeTo(null);

        //  txtloaisanpham.setText(sp.maloaisp);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbbmakhachangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbmakhachangActionPerformed

        String name;
        String sql = "select TenKhachHang from KhachHang where MaKhachHang='" + cbbmakhachang.getSelectedItem() + "'";
        ResultSet rs = db.getData(sql);
        try {
            while (rs.next()) {
                name = rs.getString("TenKhachHang");
                txttenkhachhang.setText(name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThêmHóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_cbbmakhachangActionPerformed

    private void cbbmanhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbmanhanvienActionPerformed
        // TODO add your handling code here:
        String name;
        String sql = "select TenNhanVien from NhanVien where MaNhanVien='" + cbbmanhanvien.getSelectedItem() + "'";
        ResultSet rs = db.getData(sql);
        try {
            while (rs.next()) {
                name = rs.getString("TenNhanVien");
                txttennahnvien.setText(name);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThêmHóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cbbmanhanvienActionPerformed

    private void btThemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemChiTietActionPerformed
        // TODO add your handling code here:
        String mahd = txtmahoadon.getText();
        String loaisp = txtloaisanpham.getText().trim();
        String masp = txtmasanpham.getText().trim();
        String soluong = txtsoluong.getText().trim();
        String tensanpham = txttensanpham.getText().trim();
        String gia = txtgiaban.getText().trim();

        NumberFormat fm = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
        String thanhtien = fm.format((Integer.parseInt(gia)) * Integer.parseInt(soluong));
        String s[] = {mahd, loaisp, masp, tensanpham, soluong, gia, thanhtien};
        DefaultTableModel cbb = new DefaultTableModel();
        cbb.addColumn("Mã Hóa Đơn");
        cbb.addColumn("Loại Sản Phẩm");
        cbb.addColumn("Mã Sản Phẩm");
        cbb.addColumn("Tên Sản Phẩm");
        cbb.addColumn("Số Lượng");
        cbb.addColumn("Gía Bán");
        cbb.addColumn("Thành Tiền");
        tbl_hoadon.setModel(cbb);
        cbb.addRow(s);
        int mahd1 = Integer.parseInt(mahd);
        int masp1 = Integer.parseInt(masp);
        int gia1 = Integer.parseInt(gia);
        int soluong1 = Integer.parseInt(soluong);
        int thanhtien1 = masp1 * gia1;
        ChiTietHoaDon cthd = new ChiTietHoaDon();
        cthd.setMaHoaDon(mahd1);
        cthd.setMaSanPham(masp1);
        cthd.setSoLuong(soluong1);
        cthd.setGia(gia1);
        cthd.setThanhTien(thanhtien1);
        list.add(cthd);


    }//GEN-LAST:event_btThemChiTietActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
    
            int mahd = Integer.parseInt(txtmahoadon.getText());
            int makh = Integer.parseInt(cbbmakhachang.getSelectedItem().toString());
            int manv = Integer.parseInt(cbbmanhanvien.getSelectedItem().toString());
//        Date ngaylap=jdatengaylap.getDate();
//        SimpleDateFormat fm= new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");
//        String ngaylap1=fm.format(ngaylap.getTime());
            String ngaylap1 = TXTNGAY.getText();
            int hoanthanh;
            if (jRadioButton1.isSelected()) {
                hoanthanh = 1;
            } else {
                hoanthanh = 0;
            }
            String sql = "insert into HoaDon(MaHoaDon,MaKhachHang,MaNhanVien,NgayLapHoaDon,HoanThanh) values('" + mahd + "','" + makh + "','" + manv + "','" + ngaylap1 + "','" + hoanthanh + "')";

            int masp = Integer.parseInt(txtmasanpham.getText());
            int giaban = Integer.parseInt(txtgiaban.getText());
            int soluong = Integer.parseInt(txtsoluong.getText());
            int thanhtien = giaban * soluong;
            String tensp = txttensanpham.getText();
            String sql1 = "insert into ChiTietHoaDon(MaHoaDon,MaSanPham,SoLuong,gia,ThanhTien) values('" + mahd + "','" + masp + "','" + soluong + "','" + giaban + "','" + thanhtien + "')";
           db.ExcuteQueryUpdateDB(sql);
           db.ExcuteQueryUpdateDB(sql1);
//            String sql1 = "insert into ChiTietHoaDon(MaHoaDon,MaSanPham,SoLuong,gia,ThanhTien) values(?,?,?,?,?)";
//          
//            pre = con.prepareStatement(sql1);
//
//            for (ChiTietHoaDon ct : list) {
//                pre.setInt(1, ct.getMaHoaDon());
//                pre.setInt(2, ct.getMaSanPham());
//                pre.setInt(3, ct.getSoLuong());
//                pre.setInt(4, ct.getGia());
//                pre.setInt(5, ct.getThanhTien());
//                pre.addBatch();
//            }
//
//           
//            pre.executeUpdate();
//            JOptionPane.showConfirmDialog(this, "Thêm thành cong");
       this.setVisible(false);
       new HóaĐơn().setVisible(true);
//        } catch (SQLException ex) {
//            Logger.getLogger(ThêmHóaĐơn.class.getName()).log(Level.SEVERE, null, ex);
//        }

        
    }//GEN-LAST:event_btThemActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTNGAY;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThemChiTiet;
    private javax.swing.JComboBox<String> cbbmakhachang;
    private javax.swing.JComboBox<String> cbbmanhanvien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_hoadon;
    private javax.swing.JTextField txtgiaban;
    private javax.swing.JTextField txtloaisanpham;
    private javax.swing.JTextField txtmahoadon;
    private javax.swing.JTextField txtmasanpham;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttenkhachhang;
    private javax.swing.JTextField txttennahnvien;
    private javax.swing.JTextField txttensanpham;
    // End of variables declaration//GEN-END:variables
}
